config/routes.rb
Emailapp::Application.routes.draw do
  resources :smtp_infos

  resources :events

  get "home/index"

  get "home/about"

  resources :contacts

  resources :users

root :to => "home#index"

end

app/models/smtp_info.rb
class SmtpInfo < ActiveRecord::Base
  validates :user_name, :password, :host, :port, :authentication, :starttls, :presence => true
end

app/controllers/smtp_infos_controller.rb
class SmtpInfosController < ApplicationController
  # GET /smtp_infos
  # GET /smtp_infos.xml
  def index
    #@smtp_infos = SmtpInfo.all

    respond_to do |format|
      format.html { redirect_to(new_smtp_info_path) }
      format.xml  { head :ok }
    end
  end

  # GET /smtp_infos/1
  # GET /smtp_infos/1.xml
  def show
    @smtp_info = SmtpInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @smtp_info }
    end
  end

  # GET /smtp_infos/new
  # GET /smtp_infos/new.xml
  def new
    smtp = SmtpInfo.find(:first)
    if smtp.nil? then
      @smtp_info = SmtpInfo.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @smtp_info }
      end
    
    else
      respond_to do |format|
        format.html { redirect_to(edit_smtp_info_path(smtp)) }
        format.xml  { head :ok }
      end
    end
  end

  # GET /smtp_infos/1/edit
  def edit
    @smtp_info = SmtpInfo.find(params[:id])
  end

  # POST /smtp_infos
  # POST /smtp_infos.xml
  def create
    @smtp_info = SmtpInfo.new(params[:smtp_info])

    respond_to do |format|
      if @smtp_info.save
        format.html { redirect_to(@smtp_info, :notice => 'Smtp info was successfully created.') }
        format.xml  { render :xml => @smtp_info, :status => :created, :location => @smtp_info }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @smtp_info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /smtp_infos/1
  # PUT /smtp_infos/1.xml
  def update
    @smtp_info = SmtpInfo.find(params[:id])

    respond_to do |format|
      if @smtp_info.update_attributes(params[:smtp_info])
        format.html { redirect_to(@smtp_info, :notice => 'Smtp info was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @smtp_info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /smtp_infos/1
  # DELETE /smtp_infos/1.xml
  def destroy
    @smtp_info = SmtpInfo.find(params[:id])
    @smtp_info.destroy

    respond_to do |format|
      format.html { redirect_to(smtp_infos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/smtp_infos_helper.rb
module SmtpInfosHelper
end

app/views/smtp_infos/_form.html.erb
<%= form_for(@smtp_info) do |f| %>
  <% if @smtp_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@smtp_info.errors.count, "error") %> prohibited this smtp_info from being saved:</h2>

      <ul>
      <% @smtp_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %> <span class="example">ex: yourgmailaccount@gmail.com</span><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :host %> <span class="example">ex: smtp.gmail.com</span><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :port %> <span class="example">ex: 587</span><br />
    <%= f.text_field :port %>
  </div>
  <div class="field">
    <%= f.label :authentication %> <span class="example">ex: plain or login</span><br />
    <%= f.text_field :authentication %>
  </div>
  <div class="field">
    <%= f.label :starttls %>
    <%= f.check_box :starttls %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/smtp_infos/edit.html.erb
<h1>Configure email account</h1>

<%= render 'form' %>

<%= link_to 'Show', @smtp_info %> |
<%= link_to 'Back', smtp_infos_path %>

app/views/smtp_infos/index.html.erb
<h1>Listing smtp_infos</h1>

<table>
  <tr>
    <th>User name</th>
    <th>Password</th>
    <th>Host</th>
    <th>Port</th>
    <th>Authentication</th>
    <th>Starttls</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @smtp_infos.each do |smtp_info| %>
  <tr>
    <td><%= smtp_info.user_name %></td>
    <td><%= smtp_info.password %></td>
    <td><%= smtp_info.host %></td>
    <td><%= smtp_info.port %></td>
    <td><%= smtp_info.authentication %></td>
    <td><%= smtp_info.starttls %></td>
    <td><%= link_to 'Show', smtp_info %></td>
    <td><%= link_to 'Edit', edit_smtp_info_path(smtp_info) %></td>
    <td><%= link_to 'Destroy', smtp_info, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Smtp info', new_smtp_info_path %>

app/views/smtp_infos/new.html.erb
<h1>Set up email account</h1>

<%= render 'form' %>

<%= link_to 'Back', smtp_infos_path %>

app/views/smtp_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User name:</b>
  <%= @smtp_info.user_name %>
</p>

<p>
  <b>Password:</b>
  <%= @smtp_info.password %>
</p>

<p>
  <b>Host:</b>
  <%= @smtp_info.host %>
</p>

<p>
  <b>Port:</b>
  <%= @smtp_info.port %>
</p>

<p>
  <b>Authentication:</b>
  <%= @smtp_info.authentication %>
</p>

<p>
  <b>Starttls:</b>
  <%= @smtp_info.starttls %>
</p>


<%= link_to 'Edit', edit_smtp_info_path(@smtp_info) %>