config/routes.rb
Emailapp::Application.routes.draw do
  resources :smtp_infos

  resources :events

  get "home/index"

  get "home/about"

  resources :contacts

  resources :users

root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@events = Event.find(:all).sort_by {|e| change_date_format(e.schedule_time)} #string sorting
    @events = Event.find(:all, :order => "schedule_time ASC", :conditions => ["schedule_time >= ? AND status = 0", Date.today], :limit => 20)
    @contacts = Contact.find(:all, :order => "created_at DESC", :limit => 20)
    @smtp_info = SmtpInfo.find(:first)
  end

  def about
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>about</h1>
<p>Welcome to <b>mail minder</b>. You can use this app to schedule time-delayed email from your own web-based email account for just about any purpose. To help spark your imagination, here are some examples that our millions of customers have provided us:</p>

<div id="about-list">
	<ul>
		<li>Businesses that send out seasonal coupons</li>
		<li>Political campaigns that remind citizens to get out and vote the day of or before the election</li>
		<li>Managers and organizers who set up the reminder email for an event at the same time as the original invitation</li>
	</ul>
</div>

<p>As you can see, the uses of this app are virtually limitless. If you know you're going to need to send an email on a specific date, why wait until that day, when you may forget or not have time? Use our app to schedule your emails, and consider them as good as sent&#151;in the future.</p>

app/views/home/index.html.erb
<% if @smtp_info.nil? %>
  <div id="error_explanation">
    <h2><%= link_to "You haven't set up your email account!", new_smtp_info_path, :class => "error-link" %></h2>
  </div>
<% end %>
<%#= link_to 'delete', @smtp_info, :confirm => 'Are you sure?', :method => :delete %>

<div id="event" >
  <h2><%= link_to 'Events', events_path, :title => "See all events" %></h2>
  <%= link_to 'Create a New Event', new_event_path, :class => "create" %>
  <% @events.each do |event| %>
   <ul>
     <li class="event-item"><%= link_to raw("<span>#{event.schedule_time.to_s(:date)}</span> #{event.name}"), event %></li>
     <li class="edit"><%= link_to 'edit', edit_event_path(event) %></li>
     <li class="delete"><%= link_to 'delete', event, :confirm => 'Are you sure?', :method => :delete %></li>
   </ul>
  <% end %>
</div>

<div id="contact" >
  <h2><%= link_to 'Contacts', contacts_path, :title => "See all contacts" %></h2>
  <%= link_to 'Add a New Contact', new_contact_path, :class => "create" %>
  <% @contacts.each do |contact| %>
   <ul>
     <li class="contact-item"><%= link_to raw("#{contact.first} #{contact.last} <span>#{if !contact.birthday.nil? then contact.birthday.to_s(:bd) end}</span>"), contact %></li>
     <li class="edit"><%= link_to 'edit', edit_contact_path(contact) %></li>
     <li class="delete"><%= link_to 'delete', contact, :confirm => 'Are you sure?', :method => :delete %></li>
   </ul>
  <% end %>
</div>