config/routes.rb
Emailapp::Application.routes.draw do
  resources :smtp_infos

  resources :events

  get "home/index"

  get "home/about"

  resources :contacts

  resources :users

root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  <title>mail minder</title>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/ui-lightness/jquery-ui.css" %>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js", "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="page">

<div id="header">
<h1>mail minder</h1>
</div>


<div id="content">
<%= yield %>
</div>

<div id="navigation">
  <ul>
    <li><%= link_to "Home", home_index_path %></li>
    <li><%= link_to "About", home_about_path %></li>
    <li><%= link_to "Events", events_path, :title => "Manage your events" %></li>
    <li><%= link_to "Contacts", contacts_path, :title => "Manage your contacts" %></li>
    <li><%= link_to "Configuration", new_smtp_info_path, :title => "Configure your email account" %></li>
  </ul>
</div>

<div id="footer">
		<p>Valid W3C <a href="http://validator.w3.org/check/referer" rel="external">XHTML</a> and <a href="http://jigsaw.w3.org/css-validator/check/referer" rel="external">CSS</a></p>
</div>
</div>


</html>